package com.model;

import java.util.Date;

/**
 * TChuzhuanYuan generated by MyEclipse Persistence Tools
 */

public class TChuzhuanYuan implements java.io.Serializable
{

	// Fields

	private Integer chuzhuanYuanId;

	private String chuzhuanYuanUsername;

	private String chuzhuanYuanBiezhu;

	private String chuzhuanYuanRiqi;

	private String chuzhuanYuanOne1;

	private String chuzhuanYuanOne2;

	private String chuzhuanYuanOne3;

	private String chuzhuanYuanOne4;

	private Integer chuzhuanYuanOne5;

	private Integer chuzhuanYuanOne6;

	private Date chuzhuanYuanOne7;

	private Date chuzhuanYuanOne8;

	// Constructors

	/** default constructor */
	public TChuzhuanYuan()
	{
	}

	/** full constructor */
	public TChuzhuanYuan(String chuzhuanYuanUsername,
			String chuzhuanYuanBiezhu, String chuzhuanYuanRiqi,
			String chuzhuanYuanOne1, String chuzhuanYuanOne2,
			String chuzhuanYuanOne3, String chuzhuanYuanOne4,
			Integer chuzhuanYuanOne5, Integer chuzhuanYuanOne6,
			Date chuzhuanYuanOne7, Date chuzhuanYuanOne8)
	{
		this.chuzhuanYuanUsername = chuzhuanYuanUsername;
		this.chuzhuanYuanBiezhu = chuzhuanYuanBiezhu;
		this.chuzhuanYuanRiqi = chuzhuanYuanRiqi;
		this.chuzhuanYuanOne1 = chuzhuanYuanOne1;
		this.chuzhuanYuanOne2 = chuzhuanYuanOne2;
		this.chuzhuanYuanOne3 = chuzhuanYuanOne3;
		this.chuzhuanYuanOne4 = chuzhuanYuanOne4;
		this.chuzhuanYuanOne5 = chuzhuanYuanOne5;
		this.chuzhuanYuanOne6 = chuzhuanYuanOne6;
		this.chuzhuanYuanOne7 = chuzhuanYuanOne7;
		this.chuzhuanYuanOne8 = chuzhuanYuanOne8;
	}

	// Property accessors

	public Integer getChuzhuanYuanId()
	{
		return this.chuzhuanYuanId;
	}

	public void setChuzhuanYuanId(Integer chuzhuanYuanId)
	{
		this.chuzhuanYuanId = chuzhuanYuanId;
	}

	public String getChuzhuanYuanUsername()
	{
		return this.chuzhuanYuanUsername;
	}

	public void setChuzhuanYuanUsername(String chuzhuanYuanUsername)
	{
		this.chuzhuanYuanUsername = chuzhuanYuanUsername;
	}

	public String getChuzhuanYuanBiezhu()
	{
		return this.chuzhuanYuanBiezhu;
	}

	public void setChuzhuanYuanBiezhu(String chuzhuanYuanBiezhu)
	{
		this.chuzhuanYuanBiezhu = chuzhuanYuanBiezhu;
	}

	public String getChuzhuanYuanRiqi()
	{
		return this.chuzhuanYuanRiqi;
	}

	public void setChuzhuanYuanRiqi(String chuzhuanYuanRiqi)
	{
		this.chuzhuanYuanRiqi = chuzhuanYuanRiqi;
	}

	public String getChuzhuanYuanOne1()
	{
		return this.chuzhuanYuanOne1;
	}

	public void setChuzhuanYuanOne1(String chuzhuanYuanOne1)
	{
		this.chuzhuanYuanOne1 = chuzhuanYuanOne1;
	}

	public String getChuzhuanYuanOne2()
	{
		return this.chuzhuanYuanOne2;
	}

	public void setChuzhuanYuanOne2(String chuzhuanYuanOne2)
	{
		this.chuzhuanYuanOne2 = chuzhuanYuanOne2;
	}

	public String getChuzhuanYuanOne3()
	{
		return this.chuzhuanYuanOne3;
	}

	public void setChuzhuanYuanOne3(String chuzhuanYuanOne3)
	{
		this.chuzhuanYuanOne3 = chuzhuanYuanOne3;
	}

	public String getChuzhuanYuanOne4()
	{
		return this.chuzhuanYuanOne4;
	}

	public void setChuzhuanYuanOne4(String chuzhuanYuanOne4)
	{
		this.chuzhuanYuanOne4 = chuzhuanYuanOne4;
	}

	public Integer getChuzhuanYuanOne5()
	{
		return this.chuzhuanYuanOne5;
	}

	public void setChuzhuanYuanOne5(Integer chuzhuanYuanOne5)
	{
		this.chuzhuanYuanOne5 = chuzhuanYuanOne5;
	}

	public Integer getChuzhuanYuanOne6()
	{
		return this.chuzhuanYuanOne6;
	}

	public void setChuzhuanYuanOne6(Integer chuzhuanYuanOne6)
	{
		this.chuzhuanYuanOne6 = chuzhuanYuanOne6;
	}

	public Date getChuzhuanYuanOne7()
	{
		return this.chuzhuanYuanOne7;
	}

	public void setChuzhuanYuanOne7(Date chuzhuanYuanOne7)
	{
		this.chuzhuanYuanOne7 = chuzhuanYuanOne7;
	}

	public Date getChuzhuanYuanOne8()
	{
		return this.chuzhuanYuanOne8;
	}

	public void setChuzhuanYuanOne8(Date chuzhuanYuanOne8)
	{
		this.chuzhuanYuanOne8 = chuzhuanYuanOne8;
	}

}