package com.model;

import java.util.Date;

/**
 * TFeiyong generated by MyEclipse Persistence Tools
 */

public class TFeiyong implements java.io.Serializable
{

	// Fields

	private Integer feiyongId;

	private String feiyongDate;

	private String feiyongName;

	private Integer feiyongMoney;

	private Integer feiyongBingrenId;

	private String feiyongBingrenName;

	private String one1;

	private String one2;

	private String one3;

	private String one4;

	private Integer one5;

	private Integer one6;

	private Date one7;

	private Date one8;

	// Constructors

	/** default constructor */
	public TFeiyong()
	{
	}

	/** full constructor */
	public TFeiyong(String feiyongDate, String feiyongName,
			Integer feiyongMoney, Integer feiyongBingrenId,
			String feiyongBingrenName, String one1, String one2, String one3,
			String one4, Integer one5, Integer one6, Date one7, Date one8)
	{
		this.feiyongDate = feiyongDate;
		this.feiyongName = feiyongName;
		this.feiyongMoney = feiyongMoney;
		this.feiyongBingrenId = feiyongBingrenId;
		this.feiyongBingrenName = feiyongBingrenName;
		this.one1 = one1;
		this.one2 = one2;
		this.one3 = one3;
		this.one4 = one4;
		this.one5 = one5;
		this.one6 = one6;
		this.one7 = one7;
		this.one8 = one8;
	}

	// Property accessors

	public Integer getFeiyongId()
	{
		return this.feiyongId;
	}

	public void setFeiyongId(Integer feiyongId)
	{
		this.feiyongId = feiyongId;
	}

	public String getFeiyongDate()
	{
		return this.feiyongDate;
	}

	public void setFeiyongDate(String feiyongDate)
	{
		this.feiyongDate = feiyongDate;
	}

	public String getFeiyongName()
	{
		return this.feiyongName;
	}

	public void setFeiyongName(String feiyongName)
	{
		this.feiyongName = feiyongName;
	}

	public Integer getFeiyongMoney()
	{
		return this.feiyongMoney;
	}

	public void setFeiyongMoney(Integer feiyongMoney)
	{
		this.feiyongMoney = feiyongMoney;
	}

	public Integer getFeiyongBingrenId()
	{
		return this.feiyongBingrenId;
	}

	public void setFeiyongBingrenId(Integer feiyongBingrenId)
	{
		this.feiyongBingrenId = feiyongBingrenId;
	}

	public String getFeiyongBingrenName()
	{
		return this.feiyongBingrenName;
	}

	public void setFeiyongBingrenName(String feiyongBingrenName)
	{
		this.feiyongBingrenName = feiyongBingrenName;
	}

	public String getOne1()
	{
		return this.one1;
	}

	public void setOne1(String one1)
	{
		this.one1 = one1;
	}

	public String getOne2()
	{
		return this.one2;
	}

	public void setOne2(String one2)
	{
		this.one2 = one2;
	}

	public String getOne3()
	{
		return this.one3;
	}

	public void setOne3(String one3)
	{
		this.one3 = one3;
	}

	public String getOne4()
	{
		return this.one4;
	}

	public void setOne4(String one4)
	{
		this.one4 = one4;
	}

	public Integer getOne5()
	{
		return this.one5;
	}

	public void setOne5(Integer one5)
	{
		this.one5 = one5;
	}

	public Integer getOne6()
	{
		return this.one6;
	}

	public void setOne6(Integer one6)
	{
		this.one6 = one6;
	}

	public Date getOne7()
	{
		return this.one7;
	}

	public void setOne7(Date one7)
	{
		this.one7 = one7;
	}

	public Date getOne8()
	{
		return this.one8;
	}

	public void setOne8(Date one8)
	{
		this.one8 = one8;
	}

}