package com.model;

import java.util.Date;

/**
 * TGongfei generated by MyEclipse Persistence Tools
 */

public class TGongfei implements java.io.Serializable
{

	// Fields

	private Integer gongfieId;

	private String gongfeiShiyou;

	private String gongfeiJinE;

	private String gongfeiRiqi;

	private String gongfeiOne1;//±®œ˙»À

	private String gongfeiOne2;

	private String gongfeiOne3;

	private String gongfeiOne4;

	private Integer gongfeiOne5;

	private Integer gongfeiOne6;

	private Date gongfeiOne7;

	private Long gongfeiOne8;

	// Constructors

	/** default constructor */
	public TGongfei()
	{
	}

	/** full constructor */
	public TGongfei(String gongfeiShiyou, String gongfeiJinE,
			String gongfeiRiqi, String gongfeiOne1, String gongfeiOne2,
			String gongfeiOne3, String gongfeiOne4, Integer gongfeiOne5,
			Integer gongfeiOne6, Date gongfeiOne7, Long gongfeiOne8)
	{
		this.gongfeiShiyou = gongfeiShiyou;
		this.gongfeiJinE = gongfeiJinE;
		this.gongfeiRiqi = gongfeiRiqi;
		this.gongfeiOne1 = gongfeiOne1;
		this.gongfeiOne2 = gongfeiOne2;
		this.gongfeiOne3 = gongfeiOne3;
		this.gongfeiOne4 = gongfeiOne4;
		this.gongfeiOne5 = gongfeiOne5;
		this.gongfeiOne6 = gongfeiOne6;
		this.gongfeiOne7 = gongfeiOne7;
		this.gongfeiOne8 = gongfeiOne8;
	}

	// Property accessors

	public Integer getGongfieId()
	{
		return this.gongfieId;
	}

	public void setGongfieId(Integer gongfieId)
	{
		this.gongfieId = gongfieId;
	}

	public String getGongfeiShiyou()
	{
		return this.gongfeiShiyou;
	}

	public void setGongfeiShiyou(String gongfeiShiyou)
	{
		this.gongfeiShiyou = gongfeiShiyou;
	}

	public String getGongfeiJinE()
	{
		return this.gongfeiJinE;
	}

	public void setGongfeiJinE(String gongfeiJinE)
	{
		this.gongfeiJinE = gongfeiJinE;
	}

	public String getGongfeiRiqi()
	{
		return this.gongfeiRiqi;
	}

	public void setGongfeiRiqi(String gongfeiRiqi)
	{
		this.gongfeiRiqi = gongfeiRiqi;
	}

	public String getGongfeiOne1()
	{
		return this.gongfeiOne1;
	}

	public void setGongfeiOne1(String gongfeiOne1)
	{
		this.gongfeiOne1 = gongfeiOne1;
	}

	public String getGongfeiOne2()
	{
		return this.gongfeiOne2;
	}

	public void setGongfeiOne2(String gongfeiOne2)
	{
		this.gongfeiOne2 = gongfeiOne2;
	}

	public String getGongfeiOne3()
	{
		return this.gongfeiOne3;
	}

	public void setGongfeiOne3(String gongfeiOne3)
	{
		this.gongfeiOne3 = gongfeiOne3;
	}

	public String getGongfeiOne4()
	{
		return this.gongfeiOne4;
	}

	public void setGongfeiOne4(String gongfeiOne4)
	{
		this.gongfeiOne4 = gongfeiOne4;
	}

	public Integer getGongfeiOne5()
	{
		return this.gongfeiOne5;
	}

	public void setGongfeiOne5(Integer gongfeiOne5)
	{
		this.gongfeiOne5 = gongfeiOne5;
	}

	public Integer getGongfeiOne6()
	{
		return this.gongfeiOne6;
	}

	public void setGongfeiOne6(Integer gongfeiOne6)
	{
		this.gongfeiOne6 = gongfeiOne6;
	}

	public Date getGongfeiOne7()
	{
		return this.gongfeiOne7;
	}

	public void setGongfeiOne7(Date gongfeiOne7)
	{
		this.gongfeiOne7 = gongfeiOne7;
	}

	public Long getGongfeiOne8()
	{
		return this.gongfeiOne8;
	}

	public void setGongfeiOne8(Long gongfeiOne8)
	{
		this.gongfeiOne8 = gongfeiOne8;
	}

}