package com.model;

/**
 * TRuyuan generated by MyEclipse Persistence Tools
 */

public class TRuyuan implements java.io.Serializable
{

	// Fields

	private Integer ruyuanId;

	private String ruyuanBinghaoName;

	private String ruyuanBinghaoAge;

	private String ruyuanBinghaoTel;

	private String ruyuanBinghaoSex;

	private String ruyuanYajin;

	private String ruyuanDate;

	private String one1;

	private String one2;

	private String one3;

	private String one4;

	private String one5;

	private Integer one6;

	private Integer one7;

	private String one8;

	private String one9;

	// Constructors

	/** default constructor */
	public TRuyuan()
	{
	}

	/** full constructor */
	public TRuyuan(String ruyuanBinghaoName, String ruyuanBinghaoAge,
			String ruyuanBinghaoTel, String ruyuanBinghaoSex,
			String ruyuanYajin, String ruyuanDate, String one1, String one2,
			String one3, String one4, String one5, Integer one6, Integer one7,
			String one8, String one9)
	{
		this.ruyuanBinghaoName = ruyuanBinghaoName;
		this.ruyuanBinghaoAge = ruyuanBinghaoAge;
		this.ruyuanBinghaoTel = ruyuanBinghaoTel;
		this.ruyuanBinghaoSex = ruyuanBinghaoSex;
		this.ruyuanYajin = ruyuanYajin;
		this.ruyuanDate = ruyuanDate;
		this.one1 = one1;
		this.one2 = one2;
		this.one3 = one3;
		this.one4 = one4;
		this.one5 = one5;
		this.one6 = one6;
		this.one7 = one7;
		this.one8 = one8;
		this.one9 = one9;
	}

	// Property accessors

	public Integer getRuyuanId()
	{
		return this.ruyuanId;
	}

	public void setRuyuanId(Integer ruyuanId)
	{
		this.ruyuanId = ruyuanId;
	}

	public String getRuyuanBinghaoName()
	{
		return this.ruyuanBinghaoName;
	}

	public void setRuyuanBinghaoName(String ruyuanBinghaoName)
	{
		this.ruyuanBinghaoName = ruyuanBinghaoName;
	}

	public String getRuyuanBinghaoAge()
	{
		return this.ruyuanBinghaoAge;
	}

	public void setRuyuanBinghaoAge(String ruyuanBinghaoAge)
	{
		this.ruyuanBinghaoAge = ruyuanBinghaoAge;
	}

	public String getRuyuanBinghaoTel()
	{
		return this.ruyuanBinghaoTel;
	}

	public void setRuyuanBinghaoTel(String ruyuanBinghaoTel)
	{
		this.ruyuanBinghaoTel = ruyuanBinghaoTel;
	}

	public String getRuyuanBinghaoSex()
	{
		return this.ruyuanBinghaoSex;
	}

	public void setRuyuanBinghaoSex(String ruyuanBinghaoSex)
	{
		this.ruyuanBinghaoSex = ruyuanBinghaoSex;
	}

	public String getRuyuanYajin()
	{
		return this.ruyuanYajin;
	}

	public void setRuyuanYajin(String ruyuanYajin)
	{
		this.ruyuanYajin = ruyuanYajin;
	}

	public String getRuyuanDate()
	{
		return this.ruyuanDate;
	}

	public void setRuyuanDate(String ruyuanDate)
	{
		this.ruyuanDate = ruyuanDate;
	}

	public String getOne1()
	{
		return this.one1;
	}

	public void setOne1(String one1)
	{
		this.one1 = one1;
	}

	public String getOne2()
	{
		return this.one2;
	}

	public void setOne2(String one2)
	{
		this.one2 = one2;
	}

	public String getOne3()
	{
		return this.one3;
	}

	public void setOne3(String one3)
	{
		this.one3 = one3;
	}

	public String getOne4()
	{
		return this.one4;
	}

	public void setOne4(String one4)
	{
		this.one4 = one4;
	}

	public String getOne5()
	{
		return this.one5;
	}

	public void setOne5(String one5)
	{
		this.one5 = one5;
	}

	public Integer getOne6()
	{
		return this.one6;
	}

	public void setOne6(Integer one6)
	{
		this.one6 = one6;
	}

	public Integer getOne7()
	{
		return this.one7;
	}

	public void setOne7(Integer one7)
	{
		this.one7 = one7;
	}

	public String getOne8()
	{
		return this.one8;
	}

	public void setOne8(String one8)
	{
		this.one8 = one8;
	}

	public String getOne9()
	{
		return this.one9;
	}

	public void setOne9(String one9)
	{
		this.one9 = one9;
	}

}