package com.model;

import java.util.Date;

/**
 * TYaopin generated by MyEclipse Persistence Tools
 */

public class TYaopin implements java.io.Serializable
{

	// Fields

	private Integer yaopinId;

	private String yaopinName;

	private String yaopinDanwei;

	private String yaopinJiege;

	private String yaopinShuliang;

	private String yaopinUser;

	private String yaopinRukudate;

	private String yaopinOne1;

	private String yaopinOne2;

	private String yaopinOne3;

	private String yaopinOne4;

	private Integer yaopinOne5;

	private Integer yaopinOne6;

	private Date yaopinOne7;

	private Date yaopinOne8;

	// Constructors

	/** default constructor */
	public TYaopin()
	{
	}

	/** full constructor */
	public TYaopin(String yaopinName, String yaopinDanwei, String yaopinJiege,
			String yaopinShuliang, String yaopinUser, String yaopinRukudate,
			String yaopinOne1, String yaopinOne2, String yaopinOne3,
			String yaopinOne4, Integer yaopinOne5, Integer yaopinOne6,
			Date yaopinOne7, Date yaopinOne8)
	{
		this.yaopinName = yaopinName;
		this.yaopinDanwei = yaopinDanwei;
		this.yaopinJiege = yaopinJiege;
		this.yaopinShuliang = yaopinShuliang;
		this.yaopinUser = yaopinUser;
		this.yaopinRukudate = yaopinRukudate;
		this.yaopinOne1 = yaopinOne1;
		this.yaopinOne2 = yaopinOne2;
		this.yaopinOne3 = yaopinOne3;
		this.yaopinOne4 = yaopinOne4;
		this.yaopinOne5 = yaopinOne5;
		this.yaopinOne6 = yaopinOne6;
		this.yaopinOne7 = yaopinOne7;
		this.yaopinOne8 = yaopinOne8;
	}

	// Property accessors

	public Integer getYaopinId()
	{
		return this.yaopinId;
	}

	public void setYaopinId(Integer yaopinId)
	{
		this.yaopinId = yaopinId;
	}

	public String getYaopinName()
	{
		return this.yaopinName;
	}

	public void setYaopinName(String yaopinName)
	{
		this.yaopinName = yaopinName;
	}

	public String getYaopinDanwei()
	{
		return this.yaopinDanwei;
	}

	public void setYaopinDanwei(String yaopinDanwei)
	{
		this.yaopinDanwei = yaopinDanwei;
	}

	public String getYaopinJiege()
	{
		return this.yaopinJiege;
	}

	public void setYaopinJiege(String yaopinJiege)
	{
		this.yaopinJiege = yaopinJiege;
	}

	public String getYaopinShuliang()
	{
		return this.yaopinShuliang;
	}

	public void setYaopinShuliang(String yaopinShuliang)
	{
		this.yaopinShuliang = yaopinShuliang;
	}

	public String getYaopinUser()
	{
		return this.yaopinUser;
	}

	public void setYaopinUser(String yaopinUser)
	{
		this.yaopinUser = yaopinUser;
	}

	public String getYaopinRukudate()
	{
		return this.yaopinRukudate;
	}

	public void setYaopinRukudate(String yaopinRukudate)
	{
		this.yaopinRukudate = yaopinRukudate;
	}

	public String getYaopinOne1()
	{
		return this.yaopinOne1;
	}

	public void setYaopinOne1(String yaopinOne1)
	{
		this.yaopinOne1 = yaopinOne1;
	}

	public String getYaopinOne2()
	{
		return this.yaopinOne2;
	}

	public void setYaopinOne2(String yaopinOne2)
	{
		this.yaopinOne2 = yaopinOne2;
	}

	public String getYaopinOne3()
	{
		return this.yaopinOne3;
	}

	public void setYaopinOne3(String yaopinOne3)
	{
		this.yaopinOne3 = yaopinOne3;
	}

	public String getYaopinOne4()
	{
		return this.yaopinOne4;
	}

	public void setYaopinOne4(String yaopinOne4)
	{
		this.yaopinOne4 = yaopinOne4;
	}

	public Integer getYaopinOne5()
	{
		return this.yaopinOne5;
	}

	public void setYaopinOne5(Integer yaopinOne5)
	{
		this.yaopinOne5 = yaopinOne5;
	}

	public Integer getYaopinOne6()
	{
		return this.yaopinOne6;
	}

	public void setYaopinOne6(Integer yaopinOne6)
	{
		this.yaopinOne6 = yaopinOne6;
	}

	public Date getYaopinOne7()
	{
		return this.yaopinOne7;
	}

	public void setYaopinOne7(Date yaopinOne7)
	{
		this.yaopinOne7 = yaopinOne7;
	}

	public Date getYaopinOne8()
	{
		return this.yaopinOne8;
	}

	public void setYaopinOne8(Date yaopinOne8)
	{
		this.yaopinOne8 = yaopinOne8;
	}

}