package com.model;

import java.util.Date;

/**
 * TYuangong generated by MyEclipse Persistence Tools
 */

public class TYuangong implements java.io.Serializable
{

	// Fields

	private Integer yuangongId;

	private String yuangongName;

	private String yuangongSex;

	private String yuangongAge;

	private String yuangongTel;

	private String yuangongZhiwei;

	private String yuangongOne1;

	private String yuangongOne2;

	private String yuangongOne3;

	private String yuangongOne4;

	private String yuangongOne5;

	private String yuangongOne6;

	private Integer yuangongOne7;

	private Integer yuangongOne8;

	private Date yuangongOne9;

	private Date yuangongOne10;

	// Constructors

	/** default constructor */
	public TYuangong()
	{
	}

	/** full constructor */
	public TYuangong(String yuangongName, String yuangongSex,
			String yuangongAge, String yuangongTel, String yuangongZhiwei,
			String yuangongOne1, String yuangongOne2, String yuangongOne3,
			String yuangongOne4, String yuangongOne5, String yuangongOne6,
			Integer yuangongOne7, Integer yuangongOne8, Date yuangongOne9,
			Date yuangongOne10)
	{
		this.yuangongName = yuangongName;
		this.yuangongSex = yuangongSex;
		this.yuangongAge = yuangongAge;
		this.yuangongTel = yuangongTel;
		this.yuangongZhiwei = yuangongZhiwei;
		this.yuangongOne1 = yuangongOne1;
		this.yuangongOne2 = yuangongOne2;
		this.yuangongOne3 = yuangongOne3;
		this.yuangongOne4 = yuangongOne4;
		this.yuangongOne5 = yuangongOne5;
		this.yuangongOne6 = yuangongOne6;
		this.yuangongOne7 = yuangongOne7;
		this.yuangongOne8 = yuangongOne8;
		this.yuangongOne9 = yuangongOne9;
		this.yuangongOne10 = yuangongOne10;
	}

	// Property accessors

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getYuangongName()
	{
		return this.yuangongName;
	}

	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}

	public String getYuangongSex()
	{
		return this.yuangongSex;
	}

	public void setYuangongSex(String yuangongSex)
	{
		this.yuangongSex = yuangongSex;
	}

	public String getYuangongAge()
	{
		return this.yuangongAge;
	}

	public void setYuangongAge(String yuangongAge)
	{
		this.yuangongAge = yuangongAge;
	}

	public String getYuangongTel()
	{
		return this.yuangongTel;
	}

	public void setYuangongTel(String yuangongTel)
	{
		this.yuangongTel = yuangongTel;
	}

	public String getYuangongZhiwei()
	{
		return this.yuangongZhiwei;
	}

	public void setYuangongZhiwei(String yuangongZhiwei)
	{
		this.yuangongZhiwei = yuangongZhiwei;
	}

	public String getYuangongOne1()
	{
		return this.yuangongOne1;
	}

	public void setYuangongOne1(String yuangongOne1)
	{
		this.yuangongOne1 = yuangongOne1;
	}

	public String getYuangongOne2()
	{
		return this.yuangongOne2;
	}

	public void setYuangongOne2(String yuangongOne2)
	{
		this.yuangongOne2 = yuangongOne2;
	}

	public String getYuangongOne3()
	{
		return this.yuangongOne3;
	}

	public void setYuangongOne3(String yuangongOne3)
	{
		this.yuangongOne3 = yuangongOne3;
	}

	public String getYuangongOne4()
	{
		return this.yuangongOne4;
	}

	public void setYuangongOne4(String yuangongOne4)
	{
		this.yuangongOne4 = yuangongOne4;
	}

	public String getYuangongOne5()
	{
		return this.yuangongOne5;
	}

	public void setYuangongOne5(String yuangongOne5)
	{
		this.yuangongOne5 = yuangongOne5;
	}

	public String getYuangongOne6()
	{
		return this.yuangongOne6;
	}

	public void setYuangongOne6(String yuangongOne6)
	{
		this.yuangongOne6 = yuangongOne6;
	}

	public Integer getYuangongOne7()
	{
		return this.yuangongOne7;
	}

	public void setYuangongOne7(Integer yuangongOne7)
	{
		this.yuangongOne7 = yuangongOne7;
	}

	public Integer getYuangongOne8()
	{
		return this.yuangongOne8;
	}

	public void setYuangongOne8(Integer yuangongOne8)
	{
		this.yuangongOne8 = yuangongOne8;
	}

	public Date getYuangongOne9()
	{
		return this.yuangongOne9;
	}

	public void setYuangongOne9(Date yuangongOne9)
	{
		this.yuangongOne9 = yuangongOne9;
	}

	public Date getYuangongOne10()
	{
		return this.yuangongOne10;
	}

	public void setYuangongOne10(Date yuangongOne10)
	{
		this.yuangongOne10 = yuangongOne10;
	}

}